### ISSUE TITLE
Exports not working in 2.4.0

### ISSUE THREAD

**Issue by Geoffsc** [gwu-libraries/sfm-docker#33]
Hi folks, exporting collection sets is currently failing for us in 2.4.0. Here's what I'm seeing in the docker log:

INFO 2021-09-30 15:50:05,865 1 message_consumer.sfm_ui_consumer Updating export with id 2aaefcb4399e4e209ef819da96acc600: completed failure
uiconsumer_1 | 
ERROR 2021-09-30 15:50:10,456 1 message_consumer.sfm_ui_consumer Error sending email: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError b14sm2237801qtk.64 - gsmtp', 'webmaster@localhost')

The only setting I saw in .env related to sending an email over gmail was the SFM email setting which by default is the following and has not changed for us since 2.3.0:
SFM_SMTP_HOST=smtp.gmail.com
SFM_EMAIL_USER=sfm_no_reply@email.gwu.edu
SFM_EMAIL_PASSWORD=password

I tried commenting these lines out and running an export again but the error didn't change so it appears to be unrelated. Any help is much appreciated and please let me know if I can provide any additional info!

**Comment by lwrubel** [comment]
Hi @Geoffsc, that is odd about the email error. It may be separate from the exports failing. (Not sure if you tried this already, but if you comment out those settings in `.env`, you'll need to stop and start the sfm_ui_1 container for the change to get picked up.) 

Concerning the export error: when you look at the docker logs for either the `sfm_twitterrestexporter_1` or `sfm_twitterstreamexporter_1` containers (not sure which kind of collection you were exporting) do you see anything relevant?

**Comment by Geoffsc** [comment]
Hi @lwrubel of those two containers I'm only seeing log updates in `sfm_twitterrestexporter_1` where it's showing everything being iterated over. The last line is:
`2021-10-01 10:17:19,342: sfmutils.warc_iter --> Iterating over /sfm-collection-set-data/collection_set/727bcf066ed545b9a2443a7970af16d6/b69d7139470a4762baa268aaa84edc3e/2021/09/25/10/008c77b21d524ce994c9da90fb34db92-20210925100136765-00000-hx8pvkrg.warc.gz`

And the export still fails. Please let me know if there's another container I should check the logs for or if I can provide anything else!

**Comment by lwrubel** [comment]
Thanks, that all looks normal. Looks like it's either a Twitter user_timeline or search collection you're exporting, if the activity is happening in the `sfm_twitterrestexporter_1` container.  In the `ui_consumer_1` log are you seeing any other errors or relevant info related to the export, aside from the failure message? And if you haven't already, would be worth checking the `sfm_ui_1` log. 

Would you be willing to send me your docker-compose.yml and a redacted version of your .env files? You could email sfm@gwu.edu.

**Comment by Geoffsc** [comment]
I just sent over our files, unfortunately I didn't see any changes in the logs you mentioned when I tried to run another export. Thanks!

**Comment by lwrubel** [comment]
Wrapping this up, glad you're back in business with the update to the internal path for `DATA_VOLUME_FORMER_COLLECTION_SET=/sfm-data/collection_set:/sfm-data/collection_set`
