### ISSUE TITLE
How to migrate the data from lower version dockers?

### ISSUE THREAD

**Issue by fishfree** [gwu-libraries/sfm-docker#34]
I followed the [instructions](https://sfm.readthedocs.io/en/stable/install.html#upgrading) here, but after running `docker-compose up -d`, everything lost, including the confientials and crawled data. :-(

**Comment by lwrubel** [comment]
Hi @fishfree, I'm sorry about the bumps in upgrading SFM. Your data should not be lost--the upgrade does not move or change anything. It just may be that SFM is not seeing it. There are important release notes for version 2.4 which describe new configurations to add to your `.env` and `docker-compose.yml` which relate to the paths to your data.  Read through the [version 2.4 release notes](https://github.com/gwu-libraries/sfm-docker/releases/tag/2.4.0) and if you have any questions, let us know.

**Comment by fishfree** [comment]
OK, thank you!
